# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\tp1_tc.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(661, 553)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.full_container = QtWidgets.QHBoxLayout()
        self.full_container.setObjectName("full_container")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Graphic = QtWidgets.QStackedWidget(Form)
        self.Graphic.setEnabled(True)
        self.Graphic.setObjectName("Graphic")
        self.verticalLayout_5.addWidget(self.Graphic)
        self.signal_response_frame = QtWidgets.QFrame(Form)
        self.signal_response_frame.setObjectName("signal_response_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.signal_response_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.signal_response_frame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.sr_frame = QtWidgets.QFrame(self.signal_response_frame)
        self.sr_frame.setObjectName("sr_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.sr_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.signal_type_box = QtWidgets.QComboBox(self.sr_frame)
        self.signal_type_box.setObjectName("signal_type_box")
        self.signal_type_box.addItem("")
        self.signal_type_box.addItem("")
        self.signal_type_box.addItem("")
        self.signal_type_box.addItem("")
        self.verticalLayout_7.addWidget(self.signal_type_box)
        self.fr_frame = QtWidgets.QFrame(self.sr_frame)
        self.fr_frame.setObjectName("fr_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.fr_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.fr_frame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.fr_box = QtWidgets.QDoubleSpinBox(self.fr_frame)
        self.fr_box.setMaximum(1000000000.0)
        self.fr_box.setObjectName("fr_box")
        self.horizontalLayout_7.addWidget(self.fr_box)
        self.verticalLayout_7.addWidget(self.fr_frame)
        self.duty_cycle = QtWidgets.QFrame(self.sr_frame)
        self.duty_cycle.setObjectName("duty_cycle")
        self.duty_cycle_box = QtWidgets.QHBoxLayout(self.duty_cycle)
        self.duty_cycle_box.setObjectName("duty_cycle_box")
        self.label_9 = QtWidgets.QLabel(self.duty_cycle)
        self.label_9.setObjectName("label_9")
        self.duty_cycle_box.addWidget(self.label_9)
        self.duty_box = QtWidgets.QDoubleSpinBox(self.duty_cycle)
        self.duty_box.setMinimum(0.0)
        self.duty_box.setMaximum(1.0)
        self.duty_box.setSingleStep(0.05)
        self.duty_box.setObjectName("duty_box")
        self.duty_cycle_box.addWidget(self.duty_box)
        self.verticalLayout_7.addWidget(self.duty_cycle)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.button_signal_response = QtWidgets.QPushButton(self.sr_frame)
        self.button_signal_response.setObjectName("button_signal_response")
        self.horizontalLayout_2.addWidget(self.button_signal_response)
        self.verticalLayout_8.addWidget(self.sr_frame)
        self.verticalLayout_5.addWidget(self.signal_response_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.full_container.addLayout(self.verticalLayout_5)
        self.right_options = QtWidgets.QFrame(Form)
        self.right_options.setObjectName("right_options")
        self.Right_side_options = QtWidgets.QVBoxLayout(self.right_options)
        self.Right_side_options.setObjectName("Right_side_options")
        self.Figure_Options = QtWidgets.QFrame(self.right_options)
        self.Figure_Options.setObjectName("Figure_Options")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Figure_Options)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.figOptionsButton = QtWidgets.QPushButton(self.Figure_Options)
        self.figOptionsButton.setObjectName("figOptionsButton")
        self.verticalLayout_4.addWidget(self.figOptionsButton)
        self.plotOptionsButton = QtWidgets.QPushButton(self.Figure_Options)
        self.plotOptionsButton.setObjectName("plotOptionsButton")
        self.verticalLayout_4.addWidget(self.plotOptionsButton)
        self.saveButton = QtWidgets.QPushButton(self.Figure_Options)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_4.addWidget(self.saveButton)
        self.horizontalFrame = QtWidgets.QFrame(self.Figure_Options)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalFrame = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.zoom_button = QtWidgets.QCheckBox(self.verticalFrame)
        self.zoom_button.setObjectName("zoom_button")
        self.verticalLayout_10.addWidget(self.zoom_button)
        self.pan_button = QtWidgets.QCheckBox(self.verticalFrame)
        self.pan_button.setObjectName("pan_button")
        self.verticalLayout_10.addWidget(self.pan_button)
        self.horizontalLayout_3.addWidget(self.verticalFrame)
        self.resetButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.verticalLayout_4.addWidget(self.horizontalFrame, 0, QtCore.Qt.AlignVCenter)
        self.Right_side_options.addWidget(self.Figure_Options, 0, QtCore.Qt.AlignVCenter)
        self.new_plot_button = QtWidgets.QPushButton(self.right_options)
        self.new_plot_button.setObjectName("new_plot_button")
        self.Right_side_options.addWidget(self.new_plot_button)
        self.data_input_frame = QtWidgets.QFrame(self.right_options)
        self.data_input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_input_frame.setMidLineWidth(0)
        self.data_input_frame.setObjectName("data_input_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.data_input_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.transfer_button = QtWidgets.QPushButton(self.data_input_frame)
        self.transfer_button.setObjectName("transfer_button")
        self.verticalLayout_3.addWidget(self.transfer_button)
        self.transfer_data = QtWidgets.QFrame(self.data_input_frame)
        self.transfer_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transfer_data.setLineWidth(4)
        self.transfer_data.setObjectName("transfer_data")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.transfer_data)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_denum = QtWidgets.QFrame(self.transfer_data)
        self.frame_denum.setObjectName("frame_denum")
        self.numerator_layout = QtWidgets.QHBoxLayout(self.frame_denum)
        self.numerator_layout.setObjectName("numerator_layout")
        self.label_3 = QtWidgets.QLabel(self.frame_denum)
        self.label_3.setObjectName("label_3")
        self.numerator_layout.addWidget(self.label_3)
        self.numerator_text = QtWidgets.QLineEdit(self.frame_denum)
        self.numerator_text.setObjectName("numerator_text")
        self.numerator_layout.addWidget(self.numerator_text)
        self.verticalLayout_6.addWidget(self.frame_denum)
        self.frame_denom = QtWidgets.QFrame(self.transfer_data)
        self.frame_denom.setObjectName("frame_denom")
        self.denominator_layout = QtWidgets.QHBoxLayout(self.frame_denom)
        self.denominator_layout.setObjectName("denominator_layout")
        self.label_4 = QtWidgets.QLabel(self.frame_denom)
        self.label_4.setObjectName("label_4")
        self.denominator_layout.addWidget(self.label_4)
        self.denom_text = QtWidgets.QLineEdit(self.frame_denom)
        self.denom_text.setObjectName("denom_text")
        self.denominator_layout.addWidget(self.denom_text)
        self.verticalLayout_6.addWidget(self.frame_denom)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalFrame1 = QtWidgets.QFrame(self.transfer_data)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.bode_button = QtWidgets.QToolButton(self.verticalFrame1)
        self.bode_button.setObjectName("bode_button")
        self.verticalLayout_9.addWidget(self.bode_button)
        self.button_active_resp = QtWidgets.QPushButton(self.verticalFrame1)
        self.button_active_resp.setObjectName("button_active_resp")
        self.verticalLayout_9.addWidget(self.button_active_resp)
        self.horizontalLayout_5.addWidget(self.verticalFrame1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.transfer_data)
        self.spice_button = QtWidgets.QPushButton(self.data_input_frame)
        self.spice_button.setObjectName("spice_button")
        self.verticalLayout_3.addWidget(self.spice_button)
        self.InputSpice = QtWidgets.QFrame(self.data_input_frame)
        self.InputSpice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputSpice.setObjectName("InputSpice")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.InputSpice)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalFrame_2 = QtWidgets.QFrame(self.InputSpice)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.X_axis_LT_input = QtWidgets.QHBoxLayout()
        self.X_axis_LT_input.setObjectName("X_axis_LT_input")
        self.label = QtWidgets.QLabel(self.verticalFrame_2)
        self.label.setObjectName("label")
        self.X_axis_LT_input.addWidget(self.label)
        self.X_axis_input_spice = QtWidgets.QComboBox(self.verticalFrame_2)
        self.X_axis_input_spice.setObjectName("X_axis_input_spice")
        self.X_axis_LT_input.addWidget(self.X_axis_input_spice)
        self.verticalLayout_2.addLayout(self.X_axis_LT_input)
        self.Y_axis_LT_input = QtWidgets.QHBoxLayout()
        self.Y_axis_LT_input.setObjectName("Y_axis_LT_input")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_2.setObjectName("label_2")
        self.Y_axis_LT_input.addWidget(self.label_2)
        self.Y_axis_input_spice = QtWidgets.QComboBox(self.verticalFrame_2)
        self.Y_axis_input_spice.setObjectName("Y_axis_input_spice")
        self.Y_axis_LT_input.addWidget(self.Y_axis_input_spice)
        self.verticalLayout_2.addLayout(self.Y_axis_LT_input)
        self.horizontalLayout_4.addWidget(self.verticalFrame_2)
        self.Plot_spice = QtWidgets.QPushButton(self.InputSpice)
        self.Plot_spice.setObjectName("Plot_spice")
        self.horizontalLayout_4.addWidget(self.Plot_spice)
        self.verticalLayout_3.addWidget(self.InputSpice, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.csv_button = QtWidgets.QPushButton(self.data_input_frame)
        self.csv_button.setObjectName("csv_button")
        self.verticalLayout_3.addWidget(self.csv_button)
        self.CSV_input = QtWidgets.QFrame(self.data_input_frame)
        self.CSV_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CSV_input.setObjectName("CSV_input")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.CSV_input)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.X_axis_csv_input = QtWidgets.QHBoxLayout()
        self.X_axis_csv_input.setObjectName("X_axis_csv_input")
        self.label_6 = QtWidgets.QLabel(self.CSV_input)
        self.label_6.setObjectName("label_6")
        self.X_axis_csv_input.addWidget(self.label_6)
        self.X_axis_input_csv = QtWidgets.QComboBox(self.CSV_input)
        self.X_axis_input_csv.setObjectName("X_axis_input_csv")
        self.X_axis_csv_input.addWidget(self.X_axis_input_csv)
        self.verticalLayout.addLayout(self.X_axis_csv_input)
        self.Y_axis_csv_input = QtWidgets.QHBoxLayout()
        self.Y_axis_csv_input.setObjectName("Y_axis_csv_input")
        self.label_5 = QtWidgets.QLabel(self.CSV_input)
        self.label_5.setObjectName("label_5")
        self.Y_axis_csv_input.addWidget(self.label_5)
        self.Y_axis_input_csv = QtWidgets.QComboBox(self.CSV_input)
        self.Y_axis_input_csv.setObjectName("Y_axis_input_csv")
        self.Y_axis_csv_input.addWidget(self.Y_axis_input_csv)
        self.verticalLayout.addLayout(self.Y_axis_csv_input)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.Plot_csv = QtWidgets.QPushButton(self.CSV_input)
        self.Plot_csv.setObjectName("Plot_csv")
        self.horizontalLayout_6.addWidget(self.Plot_csv)
        self.verticalLayout_3.addWidget(self.CSV_input, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Right_side_options.addWidget(self.data_input_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.delete_update_fram = QtWidgets.QVBoxLayout()
        self.delete_update_fram.setObjectName("delete_update_fram")
        self.delete_button = QtWidgets.QPushButton(self.right_options)
        self.delete_button.setObjectName("delete_button")
        self.delete_update_fram.addWidget(self.delete_button)
        self.exit_button = QtWidgets.QPushButton(self.right_options)
        self.exit_button.setObjectName("exit_button")
        self.delete_update_fram.addWidget(self.exit_button)
        self.Right_side_options.addLayout(self.delete_update_fram)
        self.full_container.addWidget(self.right_options, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.full_container)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; text-decoration: underline;\">Signal response</span></p></body></html>"))
        self.signal_type_box.setItemText(0, _translate("Form", "Sine"))
        self.signal_type_box.setItemText(1, _translate("Form", "Square"))
        self.signal_type_box.setItemText(2, _translate("Form", "Impulse"))
        self.signal_type_box.setItemText(3, _translate("Form", "Step"))
        self.label_8.setText(_translate("Form", "Frequency (Hz) = "))
        self.label_9.setText(_translate("Form", "Duty Cycle ="))
        self.button_signal_response.setText(_translate("Form", "Plot signal response"))
        self.figOptionsButton.setText(_translate("Form", "Figure options"))
        self.plotOptionsButton.setText(_translate("Form", "Plot options"))
        self.saveButton.setText(_translate("Form", "Save figure"))
        self.zoom_button.setText(_translate("Form", "Zoom mode"))
        self.pan_button.setText(_translate("Form", "Pan mode"))
        self.resetButton.setText(_translate("Form", "Reset"))
        self.new_plot_button.setText(_translate("Form", "New Plot"))
        self.transfer_button.setText(_translate("Form", "H(s)"))
        self.label_3.setText(_translate("Form", "Numerator"))
        self.label_4.setText(_translate("Form", "Denominator"))
        self.bode_button.setText(_translate("Form", "Plot Bode"))
        self.button_active_resp.setText(_translate("Form", "Signal Resp"))
        self.spice_button.setText(_translate("Form", "LTSpice"))
        self.label.setText(_translate("Form", "X axis"))
        self.label_2.setText(_translate("Form", "Y axis"))
        self.Plot_spice.setText(_translate("Form", "Plot LTSpice"))
        self.csv_button.setText(_translate("Form", "CSV"))
        self.label_6.setText(_translate("Form", "X axis"))
        self.label_5.setText(_translate("Form", "Y axis"))
        self.Plot_csv.setText(_translate("Form", "Plot CSV"))
        self.delete_button.setText(_translate("Form", "Clear figure"))
        self.exit_button.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
