# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\tc_tp4_mainwindow_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 446)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameTotal = QtWidgets.QFrame(Form)
        self.frameTotal.setObjectName("frameTotal")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frameTotal)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphic = QtWidgets.QStackedWidget(self.frameTotal)
        self.graphic.setObjectName("graphic")
        self.verticalLayout.addWidget(self.graphic)
        self.prev_next_frame = QtWidgets.QFrame(self.frameTotal)
        self.prev_next_frame.setObjectName("prev_next_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.prev_next_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.previous_button = QtWidgets.QPushButton(self.prev_next_frame)
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout_4.addWidget(self.previous_button)
        self.next_button = QtWidgets.QPushButton(self.prev_next_frame)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_4.addWidget(self.next_button)
        self.verticalLayout.addWidget(self.prev_next_frame)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.frame_menu_tot = QtWidgets.QFrame(self.frameTotal)
        self.frame_menu_tot.setObjectName("frame_menu_tot")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_menu_tot)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuFrame = QtWidgets.QFrame(self.frame_menu_tot)
        self.menuFrame.setObjectName("menuFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.menuFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Filter_Approx_Menu = QtWidgets.QFrame(self.menuFrame)
        self.Filter_Approx_Menu.setObjectName("Filter_Approx_Menu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Filter_Approx_Menu)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filterTypeFrame = QtWidgets.QFrame(self.Filter_Approx_Menu)
        self.filterTypeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filterTypeFrame.setObjectName("filterTypeFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.filterTypeFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.filterTypeFrame)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.filterType = QtWidgets.QComboBox(self.filterTypeFrame)
        self.filterType.setObjectName("filterType")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.verticalLayout_3.addWidget(self.filterType)
        self.horizontalLayout_2.addWidget(self.filterTypeFrame, 0, QtCore.Qt.AlignVCenter)
        self.approxTypeFrame = QtWidgets.QFrame(self.Filter_Approx_Menu)
        self.approxTypeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.approxTypeFrame.setObjectName("approxTypeFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.approxTypeFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.approxTypeFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.approxType = QtWidgets.QComboBox(self.approxTypeFrame)
        self.approxType.setObjectName("approxType")
        self.approxType.addItem("")
        self.approxType.addItem("")
        self.approxType.addItem("")
        self.approxType.addItem("")
        self.approxType.addItem("")
        self.verticalLayout_4.addWidget(self.approxType)
        self.horizontalLayout_2.addWidget(self.approxTypeFrame, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_5.addWidget(self.Filter_Approx_Menu, 0, QtCore.Qt.AlignVCenter)
        self.parameters_frame = QtWidgets.QFrame(self.menuFrame)
        self.parameters_frame.setObjectName("parameters_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.parameters_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wp_frame = QtWidgets.QFrame(self.parameters_frame)
        self.wp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wp_frame.setObjectName("wp_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.wp_frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.wp_frame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.wp_value = QtWidgets.QDoubleSpinBox(self.wp_frame)
        self.wp_value.setAlignment(QtCore.Qt.AlignCenter)
        self.wp_value.setMinimum(0.1)
        self.wp_value.setMaximum(200.0)
        self.wp_value.setSingleStep(0.1)
        self.wp_value.setObjectName("wp_value")
        self.verticalLayout_11.addWidget(self.wp_value)
        self.horizontalLayout_3.addWidget(self.wp_frame)
        self.ws_frame = QtWidgets.QFrame(self.parameters_frame)
        self.ws_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ws_frame.setObjectName("ws_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.ws_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.ws_frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.ws_value = QtWidgets.QDoubleSpinBox(self.ws_frame)
        self.ws_value.setAlignment(QtCore.Qt.AlignCenter)
        self.ws_value.setMinimum(0.2)
        self.ws_value.setMaximum(200.0)
        self.ws_value.setSingleStep(0.1)
        self.ws_value.setObjectName("ws_value")
        self.verticalLayout_10.addWidget(self.ws_value)
        self.horizontalLayout_3.addWidget(self.ws_frame)
        self.ap_frame = QtWidgets.QFrame(self.parameters_frame)
        self.ap_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ap_frame.setObjectName("ap_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.ap_frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.ap_frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.ap_value = QtWidgets.QDoubleSpinBox(self.ap_frame)
        self.ap_value.setAlignment(QtCore.Qt.AlignCenter)
        self.ap_value.setMinimum(0.1)
        self.ap_value.setMaximum(10.0)
        self.ap_value.setSingleStep(0.1)
        self.ap_value.setObjectName("ap_value")
        self.verticalLayout_9.addWidget(self.ap_value)
        self.horizontalLayout_3.addWidget(self.ap_frame)
        self.as_frame = QtWidgets.QFrame(self.parameters_frame)
        self.as_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.as_frame.setObjectName("as_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.as_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.as_frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.as_value = QtWidgets.QDoubleSpinBox(self.as_frame)
        self.as_value.setAlignment(QtCore.Qt.AlignCenter)
        self.as_value.setMinimum(10.0)
        self.as_value.setMaximum(100.0)
        self.as_value.setSingleStep(0.1)
        self.as_value.setObjectName("as_value")
        self.verticalLayout_8.addWidget(self.as_value)
        self.horizontalLayout_3.addWidget(self.as_frame)
        self.verticalLayout_5.addWidget(self.parameters_frame, 0, QtCore.Qt.AlignVCenter)
        self.parameters_BP_SB_frame = QtWidgets.QFrame(self.menuFrame)
        self.parameters_BP_SB_frame.setObjectName("parameters_BP_SB_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.parameters_BP_SB_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ws_min_bp_bs_frame = QtWidgets.QFrame(self.parameters_BP_SB_frame)
        self.ws_min_bp_bs_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ws_min_bp_bs_frame.setObjectName("ws_min_bp_bs_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.ws_min_bp_bs_frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.ws_min_bp_bs_frame)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.wsmin_value = QtWidgets.QDoubleSpinBox(self.ws_min_bp_bs_frame)
        self.wsmin_value.setAlignment(QtCore.Qt.AlignCenter)
        self.wsmin_value.setMinimum(0.1)
        self.wsmin_value.setMaximum(200.0)
        self.wsmin_value.setSingleStep(0.1)
        self.wsmin_value.setObjectName("wsmin_value")
        self.verticalLayout_13.addWidget(self.wsmin_value)
        self.horizontalLayout_5.addWidget(self.ws_min_bp_bs_frame)
        self.wp_min_frame = QtWidgets.QFrame(self.parameters_BP_SB_frame)
        self.wp_min_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wp_min_frame.setObjectName("wp_min_frame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.wp_min_frame)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.wp_min_frame)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.wpmin_value = QtWidgets.QDoubleSpinBox(self.wp_min_frame)
        self.wpmin_value.setAlignment(QtCore.Qt.AlignCenter)
        self.wpmin_value.setMinimum(0.2)
        self.wpmin_value.setMaximum(200.0)
        self.wpmin_value.setSingleStep(0.1)
        self.wpmin_value.setObjectName("wpmin_value")
        self.verticalLayout_15.addWidget(self.wpmin_value)
        self.horizontalLayout_5.addWidget(self.wp_min_frame)
        self.wp_bp_bs_plus_frame = QtWidgets.QFrame(self.parameters_BP_SB_frame)
        self.wp_bp_bs_plus_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wp_bp_bs_plus_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.wp_bp_bs_plus_frame.setLineWidth(3)
        self.wp_bp_bs_plus_frame.setMidLineWidth(0)
        self.wp_bp_bs_plus_frame.setObjectName("wp_bp_bs_plus_frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.wp_bp_bs_plus_frame)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_8 = QtWidgets.QLabel(self.wp_bp_bs_plus_frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_16.addWidget(self.label_8)
        self.wpmax_value = QtWidgets.QDoubleSpinBox(self.wp_bp_bs_plus_frame)
        self.wpmax_value.setAlignment(QtCore.Qt.AlignCenter)
        self.wpmax_value.setMinimum(0.3)
        self.wpmax_value.setMaximum(200.0)
        self.wpmax_value.setSingleStep(0.1)
        self.wpmax_value.setObjectName("wpmax_value")
        self.verticalLayout_16.addWidget(self.wpmax_value)
        self.horizontalLayout_5.addWidget(self.wp_bp_bs_plus_frame)
        self.ws_plus_bp_bs_frame = QtWidgets.QFrame(self.parameters_BP_SB_frame)
        self.ws_plus_bp_bs_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ws_plus_bp_bs_frame.setObjectName("ws_plus_bp_bs_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ws_plus_bp_bs_frame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.ws_plus_bp_bs_frame)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.wsmax_value = QtWidgets.QDoubleSpinBox(self.ws_plus_bp_bs_frame)
        self.wsmax_value.setAlignment(QtCore.Qt.AlignCenter)
        self.wsmax_value.setMinimum(0.4)
        self.wsmax_value.setMaximum(200.0)
        self.wsmax_value.setSingleStep(0.1)
        self.wsmax_value.setObjectName("wsmax_value")
        self.verticalLayout_14.addWidget(self.wsmax_value)
        self.horizontalLayout_5.addWidget(self.ws_plus_bp_bs_frame)
        self.ap_bp_bs_frame = QtWidgets.QFrame(self.parameters_BP_SB_frame)
        self.ap_bp_bs_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ap_bp_bs_frame.setObjectName("ap_bp_bs_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.ap_bp_bs_frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.ap_bp_bs_frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.ap_bp_bs_value = QtWidgets.QDoubleSpinBox(self.ap_bp_bs_frame)
        self.ap_bp_bs_value.setAlignment(QtCore.Qt.AlignCenter)
        self.ap_bp_bs_value.setMinimum(0.1)
        self.ap_bp_bs_value.setMaximum(10.0)
        self.ap_bp_bs_value.setSingleStep(0.1)
        self.ap_bp_bs_value.setObjectName("ap_bp_bs_value")
        self.verticalLayout_12.addWidget(self.ap_bp_bs_value)
        self.horizontalLayout_5.addWidget(self.ap_bp_bs_frame)
        self.as_bp_bs_frame = QtWidgets.QFrame(self.parameters_BP_SB_frame)
        self.as_bp_bs_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.as_bp_bs_frame.setObjectName("as_bp_bs_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.as_bp_bs_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.as_bp_bs_frame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.as_bp_bs_value = QtWidgets.QDoubleSpinBox(self.as_bp_bs_frame)
        self.as_bp_bs_value.setAlignment(QtCore.Qt.AlignCenter)
        self.as_bp_bs_value.setMinimum(10.0)
        self.as_bp_bs_value.setMaximum(100.0)
        self.as_bp_bs_value.setSingleStep(0.1)
        self.as_bp_bs_value.setObjectName("as_bp_bs_value")
        self.verticalLayout_7.addWidget(self.as_bp_bs_value)
        self.horizontalLayout_5.addWidget(self.as_bp_bs_frame)
        self.verticalLayout_5.addWidget(self.parameters_BP_SB_frame, 0, QtCore.Qt.AlignVCenter)
        self.parameters_GD_frame_2 = QtWidgets.QFrame(self.menuFrame)
        self.parameters_GD_frame_2.setObjectName("parameters_GD_frame_2")
        self.parameters_GD_frame = QtWidgets.QHBoxLayout(self.parameters_GD_frame_2)
        self.parameters_GD_frame.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.parameters_GD_frame.setObjectName("parameters_GD_frame")
        self.frame_tau0 = QtWidgets.QFrame(self.parameters_GD_frame_2)
        self.frame_tau0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tau0.setObjectName("frame_tau0")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_tau0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_13 = QtWidgets.QLabel(self.frame_tau0)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_18.addWidget(self.label_13)
        self.t0_value = QtWidgets.QDoubleSpinBox(self.frame_tau0)
        self.t0_value.setAlignment(QtCore.Qt.AlignCenter)
        self.t0_value.setMinimum(0.01)
        self.t0_value.setObjectName("t0_value")
        self.verticalLayout_18.addWidget(self.t0_value)
        self.parameters_GD_frame.addWidget(self.frame_tau0)
        self.frame_max_err_tau = QtWidgets.QFrame(self.parameters_GD_frame_2)
        self.frame_max_err_tau.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_max_err_tau.setObjectName("frame_max_err_tau")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_max_err_tau)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_14 = QtWidgets.QLabel(self.frame_max_err_tau)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_24.addWidget(self.label_14)
        self.error_tau_value = QtWidgets.QDoubleSpinBox(self.frame_max_err_tau)
        self.error_tau_value.setAlignment(QtCore.Qt.AlignCenter)
        self.error_tau_value.setMinimum(0.01)
        self.error_tau_value.setMaximum(100.0)
        self.error_tau_value.setSingleStep(0.01)
        self.error_tau_value.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.error_tau_value.setObjectName("error_tau_value")
        self.verticalLayout_24.addWidget(self.error_tau_value)
        self.parameters_GD_frame.addWidget(self.frame_max_err_tau)
        self.omega_gd_frame = QtWidgets.QFrame(self.parameters_GD_frame_2)
        self.omega_gd_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.omega_gd_frame.setObjectName("omega_gd_frame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.omega_gd_frame)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_15 = QtWidgets.QLabel(self.omega_gd_frame)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_17.addWidget(self.label_15)
        self.omega_gd_value = QtWidgets.QDoubleSpinBox(self.omega_gd_frame)
        self.omega_gd_value.setAlignment(QtCore.Qt.AlignCenter)
        self.omega_gd_value.setMinimum(0.1)
        self.omega_gd_value.setMaximum(200.0)
        self.omega_gd_value.setSingleStep(0.1)
        self.omega_gd_value.setObjectName("omega_gd_value")
        self.verticalLayout_17.addWidget(self.omega_gd_value)
        self.parameters_GD_frame.addWidget(self.omega_gd_frame)
        self.verticalLayout_5.addWidget(self.parameters_GD_frame_2)
        self.restric_frame = QtWidgets.QFrame(self.menuFrame)
        self.restric_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.restric_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.restric_frame.setObjectName("restric_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.restric_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.q_max_frame = QtWidgets.QFrame(self.restric_frame)
        self.q_max_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q_max_frame.setObjectName("q_max_frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.q_max_frame)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.qmax_checkbox = QtWidgets.QCheckBox(self.q_max_frame)
        self.qmax_checkbox.setObjectName("qmax_checkbox")
        self.verticalLayout_22.addWidget(self.qmax_checkbox)
        self.q_max_value = QtWidgets.QDoubleSpinBox(self.q_max_frame)
        self.q_max_value.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max_value.setMinimum(0.01)
        self.q_max_value.setSingleStep(0.01)
        self.q_max_value.setObjectName("q_max_value")
        self.verticalLayout_22.addWidget(self.q_max_value)
        self.horizontalLayout_6.addWidget(self.q_max_frame)
        self.order_min_frame = QtWidgets.QFrame(self.restric_frame)
        self.order_min_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.order_min_frame.setObjectName("order_min_frame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.order_min_frame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.nmin_checkbox = QtWidgets.QCheckBox(self.order_min_frame)
        self.nmin_checkbox.setObjectName("nmin_checkbox")
        self.verticalLayout_21.addWidget(self.nmin_checkbox)
        self.n_min_value = QtWidgets.QSpinBox(self.order_min_frame)
        self.n_min_value.setAlignment(QtCore.Qt.AlignCenter)
        self.n_min_value.setMinimum(1)
        self.n_min_value.setObjectName("n_min_value")
        self.verticalLayout_21.addWidget(self.n_min_value)
        self.horizontalLayout_6.addWidget(self.order_min_frame)
        self.order_max_frame = QtWidgets.QFrame(self.restric_frame)
        self.order_max_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.order_max_frame.setObjectName("order_max_frame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.order_max_frame)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.nmax_checkbox = QtWidgets.QCheckBox(self.order_max_frame)
        self.nmax_checkbox.setObjectName("nmax_checkbox")
        self.verticalLayout_20.addWidget(self.nmax_checkbox)
        self.n_max_value = QtWidgets.QSpinBox(self.order_max_frame)
        self.n_max_value.setAlignment(QtCore.Qt.AlignCenter)
        self.n_max_value.setMinimum(1)
        self.n_max_value.setObjectName("n_max_value")
        self.verticalLayout_20.addWidget(self.n_max_value)
        self.horizontalLayout_6.addWidget(self.order_max_frame)
        self.range_frame = QtWidgets.QFrame(self.restric_frame)
        self.range_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.range_frame.setObjectName("range_frame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.range_frame)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.denorm_range_checkbox = QtWidgets.QCheckBox(self.range_frame)
        self.denorm_range_checkbox.setObjectName("denorm_range_checkbox")
        self.verticalLayout_19.addWidget(self.denorm_range_checkbox)
        self.range_value = QtWidgets.QSlider(self.range_frame)
        self.range_value.setMaximum(100)
        self.range_value.setOrientation(QtCore.Qt.Horizontal)
        self.range_value.setObjectName("range_value")
        self.verticalLayout_19.addWidget(self.range_value)
        self.horizontalLayout_6.addWidget(self.range_frame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.restric_frame, 0, QtCore.Qt.AlignVCenter)
        self.frame_buttons = QtWidgets.QFrame(self.menuFrame)
        self.frame_buttons.setObjectName("frame_buttons")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_buttons)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ok_restric_frame = QtWidgets.QWidget(self.frame_buttons)
        self.ok_restric_frame.setObjectName("ok_restric_frame")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.ok_restric_frame)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.ok_go = QtWidgets.QPushButton(self.ok_restric_frame)
        self.ok_go.setObjectName("ok_go")
        self.verticalLayout_23.addWidget(self.ok_go)
        self.clear_button = QtWidgets.QPushButton(self.ok_restric_frame)
        self.clear_button.setObjectName("clear_button")
        self.verticalLayout_23.addWidget(self.clear_button)
        self.horizontalLayout_8.addWidget(self.ok_restric_frame)
        self.verticalLayout_5.addWidget(self.frame_buttons)
        self.exit_button = QtWidgets.QPushButton(self.menuFrame)
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout_5.addWidget(self.exit_button)
        self.horizontalLayout.addWidget(self.menuFrame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_7.addWidget(self.frame_menu_tot)
        self.verticalLayout_2.addWidget(self.frameTotal)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.previous_button.setText(_translate("Form", "Previous"))
        self.next_button.setText(_translate("Form", "Next"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Filter type</span></p></body></html>"))
        self.filterType.setItemText(0, _translate("Form", "Low Pass"))
        self.filterType.setItemText(1, _translate("Form", "High Pass"))
        self.filterType.setItemText(2, _translate("Form", "Band Pass"))
        self.filterType.setItemText(3, _translate("Form", "Band Stop"))
        self.filterType.setItemText(4, _translate("Form", "Group Delay"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Approximation</span></p></body></html>"))
        self.approxType.setItemText(0, _translate("Form", "Butterworth"))
        self.approxType.setItemText(1, _translate("Form", "Cheby 1"))
        self.approxType.setItemText(2, _translate("Form", "Cheby 2"))
        self.approxType.setItemText(3, _translate("Form", "Cauer"))
        self.approxType.setItemText(4, _translate("Form", "Legendre"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">ω</span><span style=\" font-size:10pt; vertical-align:sub;\">p </span><span style=\" font-size:10pt;\">[krad/seg]</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">ω</span><span style=\" font-size:10pt; vertical-align:sub;\">s </span><span style=\" font-size:10pt;\">[krad/seg]</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">A</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\"> [dB]</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">A</span><span style=\" font-size:10pt; vertical-align:sub;\">s</span><span style=\" font-size:10pt;\"> [dB]</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">ω</span><span style=\" font-size:10pt; vertical-align:sub;\">s</span><span style=\" font-size:10pt; vertical-align:super;\">- </span><span style=\" font-size:10pt;\">[krad/seg]</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">ω</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:11pt; vertical-align:super;\">- </span><span style=\" font-size:10pt;\">[krad/seg]</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">ω</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt; vertical-align:super;\">+ </span><span style=\" font-size:10pt;\">[krad/seg]</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">ω</span><span style=\" font-size:10pt; vertical-align:sub;\">s</span><span style=\" font-size:10pt; vertical-align:super;\">+ </span><span style=\" font-size:10pt;\">[krad/seg]</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">A</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\"> [dB]</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">A</span><span style=\" font-size:10pt; vertical-align:sub;\">s</span><span style=\" font-size:10pt;\"> [dB]</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">τ</span><span style=\" font-size:12pt; vertical-align:sub;\">0</span><span style=\" font-size:10pt;\"> [s]</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Máx error en </span><span style=\" font-size:12pt;\">τ</span><span style=\" font-size:9pt;\">(ω) (%)</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">ω</span><span style=\" font-size:11pt; vertical-align:sub;\">p </span><span style=\" font-size:11pt;\">[krad/seg]</span></p></body></html>"))
        self.qmax_checkbox.setText(_translate("Form", "Q max"))
        self.nmin_checkbox.setText(_translate("Form", "Order min"))
        self.nmax_checkbox.setText(_translate("Form", "Order max"))
        self.denorm_range_checkbox.setText(_translate("Form", "Denormalization Range"))
        self.ok_go.setText(_translate("Form", "Plot"))
        self.clear_button.setText(_translate("Form", "Clear"))
        self.exit_button.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
