# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tp1_tc.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(661, 553)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.full_container = QtWidgets.QHBoxLayout()
        self.full_container.setObjectName("full_container")
        self.Graphic = QtWidgets.QStackedWidget(Form)
        self.Graphic.setEnabled(True)
        self.Graphic.setObjectName("Graphic")
        self.full_container.addWidget(self.Graphic)
        self.right_options = QtWidgets.QFrame(Form)
        self.right_options.setObjectName("right_options")
        self.Right_side_options = QtWidgets.QVBoxLayout(self.right_options)
        self.Right_side_options.setObjectName("Right_side_options")
        self.Figure_Options = QtWidgets.QFrame(self.right_options)
        self.Figure_Options.setObjectName("Figure_Options")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Figure_Options)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.figOptionsButton = QtWidgets.QPushButton(self.Figure_Options)
        self.figOptionsButton.setObjectName("figOptionsButton")
        self.verticalLayout_4.addWidget(self.figOptionsButton)
        self.plotOptionsButton = QtWidgets.QPushButton(self.Figure_Options)
        self.plotOptionsButton.setObjectName("plotOptionsButton")
        self.verticalLayout_4.addWidget(self.plotOptionsButton)
        self.saveButton = QtWidgets.QPushButton(self.Figure_Options)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_4.addWidget(self.saveButton)
        self.horizontalFrame = QtWidgets.QFrame(self.Figure_Options)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zoom_button = QtWidgets.QCheckBox(self.horizontalFrame)
        self.zoom_button.setObjectName("zoom_button")
        self.horizontalLayout_3.addWidget(self.zoom_button)
        self.resetButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.verticalLayout_4.addWidget(self.horizontalFrame, 0, QtCore.Qt.AlignVCenter)
        self.Right_side_options.addWidget(self.Figure_Options, 0, QtCore.Qt.AlignVCenter)
        self.new_plot_button = QtWidgets.QPushButton(self.right_options)
        self.new_plot_button.setObjectName("new_plot_button")
        self.Right_side_options.addWidget(self.new_plot_button)
        self.data_input_frame = QtWidgets.QFrame(self.right_options)
        self.data_input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_input_frame.setMidLineWidth(0)
        self.data_input_frame.setObjectName("data_input_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.data_input_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.transfer_layout = QtWidgets.QFrame(self.data_input_frame)
        self.transfer_layout.setAutoFillBackground(False)
        self.transfer_layout.setFrameShadow(QtWidgets.QFrame.Plain)
        self.transfer_layout.setObjectName("transfer_layout")
        self.H_s_layout = QtWidgets.QVBoxLayout(self.transfer_layout)
        self.H_s_layout.setObjectName("H_s_layout")
        self.transfer_button = QtWidgets.QPushButton(self.transfer_layout)
        self.transfer_button.setObjectName("transfer_button")
        self.H_s_layout.addWidget(self.transfer_button, 0, QtCore.Qt.AlignVCenter)
        self.transfer_data = QtWidgets.QFrame(self.transfer_layout)
        self.transfer_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transfer_data.setLineWidth(4)
        self.transfer_data.setObjectName("transfer_data")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.transfer_data)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_denum = QtWidgets.QFrame(self.transfer_data)
        self.frame_denum.setObjectName("frame_denum")
        self.numerator_layout = QtWidgets.QHBoxLayout(self.frame_denum)
        self.numerator_layout.setObjectName("numerator_layout")
        self.label_3 = QtWidgets.QLabel(self.frame_denum)
        self.label_3.setObjectName("label_3")
        self.numerator_layout.addWidget(self.label_3)
        self.numerator_text = QtWidgets.QLineEdit(self.frame_denum)
        self.numerator_text.setObjectName("numerator_text")
        self.numerator_layout.addWidget(self.numerator_text)
        self.verticalLayout_6.addWidget(self.frame_denum)
        self.frame_denom = QtWidgets.QFrame(self.transfer_data)
        self.frame_denom.setObjectName("frame_denom")
        self.denominator_layout = QtWidgets.QHBoxLayout(self.frame_denom)
        self.denominator_layout.setObjectName("denominator_layout")
        self.label_4 = QtWidgets.QLabel(self.frame_denom)
        self.label_4.setObjectName("label_4")
        self.denominator_layout.addWidget(self.label_4)
        self.denom_text = QtWidgets.QLineEdit(self.frame_denom)
        self.denom_text.setObjectName("denom_text")
        self.denominator_layout.addWidget(self.denom_text)
        self.verticalLayout_6.addWidget(self.frame_denom)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.bode_button = QtWidgets.QToolButton(self.transfer_data)
        self.bode_button.setObjectName("bode_button")
        self.horizontalLayout_5.addWidget(self.bode_button)
        self.H_s_layout.addWidget(self.transfer_data, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.transfer_layout, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.spice_button = QtWidgets.QPushButton(self.data_input_frame)
        self.spice_button.setObjectName("spice_button")
        self.verticalLayout_3.addWidget(self.spice_button)
        self.InputSpice = QtWidgets.QFrame(self.data_input_frame)
        self.InputSpice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputSpice.setObjectName("InputSpice")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.InputSpice)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalFrame_2 = QtWidgets.QFrame(self.InputSpice)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.X_axis_LT_input = QtWidgets.QHBoxLayout()
        self.X_axis_LT_input.setObjectName("X_axis_LT_input")
        self.label = QtWidgets.QLabel(self.verticalFrame_2)
        self.label.setObjectName("label")
        self.X_axis_LT_input.addWidget(self.label)
        self.X_axis_input_spice = QtWidgets.QComboBox(self.verticalFrame_2)
        self.X_axis_input_spice.setObjectName("X_axis_input_spice")
        self.X_axis_LT_input.addWidget(self.X_axis_input_spice)
        self.verticalLayout_2.addLayout(self.X_axis_LT_input)
        self.Y_axis_LT_input = QtWidgets.QHBoxLayout()
        self.Y_axis_LT_input.setObjectName("Y_axis_LT_input")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_2.setObjectName("label_2")
        self.Y_axis_LT_input.addWidget(self.label_2)
        self.Y_axis_input_spice = QtWidgets.QComboBox(self.verticalFrame_2)
        self.Y_axis_input_spice.setObjectName("Y_axis_input_spice")
        self.Y_axis_LT_input.addWidget(self.Y_axis_input_spice)
        self.verticalLayout_2.addLayout(self.Y_axis_LT_input)
        self.horizontalLayout_4.addWidget(self.verticalFrame_2)
        self.Plot_spice = QtWidgets.QPushButton(self.InputSpice)
        self.Plot_spice.setObjectName("Plot_spice")
        self.horizontalLayout_4.addWidget(self.Plot_spice)
        self.verticalLayout_3.addWidget(self.InputSpice, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.csv_button = QtWidgets.QPushButton(self.data_input_frame)
        self.csv_button.setObjectName("csv_button")
        self.verticalLayout_3.addWidget(self.csv_button)
        self.CSV_input = QtWidgets.QFrame(self.data_input_frame)
        self.CSV_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CSV_input.setObjectName("CSV_input")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.CSV_input)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.X_axis_csv_input = QtWidgets.QHBoxLayout()
        self.X_axis_csv_input.setObjectName("X_axis_csv_input")
        self.label_6 = QtWidgets.QLabel(self.CSV_input)
        self.label_6.setObjectName("label_6")
        self.X_axis_csv_input.addWidget(self.label_6)
        self.X_axis_input_csv = QtWidgets.QComboBox(self.CSV_input)
        self.X_axis_input_csv.setObjectName("X_axis_input_csv")
        self.X_axis_csv_input.addWidget(self.X_axis_input_csv)
        self.verticalLayout.addLayout(self.X_axis_csv_input)
        self.Y_axis_csv_input = QtWidgets.QHBoxLayout()
        self.Y_axis_csv_input.setObjectName("Y_axis_csv_input")
        self.label_5 = QtWidgets.QLabel(self.CSV_input)
        self.label_5.setObjectName("label_5")
        self.Y_axis_csv_input.addWidget(self.label_5)
        self.Y_axis_input_csv = QtWidgets.QComboBox(self.CSV_input)
        self.Y_axis_input_csv.setObjectName("Y_axis_input_csv")
        self.Y_axis_csv_input.addWidget(self.Y_axis_input_csv)
        self.verticalLayout.addLayout(self.Y_axis_csv_input)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.Plot_csv = QtWidgets.QPushButton(self.CSV_input)
        self.Plot_csv.setObjectName("Plot_csv")
        self.horizontalLayout_6.addWidget(self.Plot_csv)
        self.verticalLayout_3.addWidget(self.CSV_input, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Right_side_options.addWidget(self.data_input_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.delete_update_fram = QtWidgets.QVBoxLayout()
        self.delete_update_fram.setObjectName("delete_update_fram")
        self.delete_button = QtWidgets.QPushButton(self.right_options)
        self.delete_button.setObjectName("delete_button")
        self.delete_update_fram.addWidget(self.delete_button)
        self.exit_button = QtWidgets.QPushButton(self.right_options)
        self.exit_button.setObjectName("exit_button")
        self.delete_update_fram.addWidget(self.exit_button)
        self.Right_side_options.addLayout(self.delete_update_fram)
        self.full_container.addWidget(self.right_options, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.full_container)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.figOptionsButton.setText(_translate("Form", "Figure options"))
        self.plotOptionsButton.setText(_translate("Form", "Plot options"))
        self.saveButton.setText(_translate("Form", "Save figure"))
        self.zoom_button.setText(_translate("Form", "Zoom mode"))
        self.resetButton.setText(_translate("Form", "Reset Zoom"))
        self.new_plot_button.setText(_translate("Form", "New Plot"))
        self.transfer_button.setText(_translate("Form", "H(s)"))
        self.label_3.setText(_translate("Form", "Numerator"))
        self.label_4.setText(_translate("Form", "Denominator"))
        self.bode_button.setText(_translate("Form", "Plot Bode"))
        self.spice_button.setText(_translate("Form", "LTSpice"))
        self.label.setText(_translate("Form", "X axis"))
        self.label_2.setText(_translate("Form", "Y axis"))
        self.Plot_spice.setText(_translate("Form", "Plot LTSpice"))
        self.csv_button.setText(_translate("Form", "CSV"))
        self.label_6.setText(_translate("Form", "X axis"))
        self.label_5.setText(_translate("Form", "Y axis"))
        self.Plot_csv.setText(_translate("Form", "Plot CSV"))
        self.delete_button.setText(_translate("Form", "Clear figure"))
        self.exit_button.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
